import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { cn } from '@/lib/utils';

/**
 * Renders a customizable table from column definitions and row data.
 *
 * The table displays a header row using `column.header` and a body where each cell is produced by `column.cell(row, rowIndex)`. Row keys are generated by the supplied `rowKey` function. Various `*ClassName` props override or extend default styling for the table, header, header cells, body rows, and body cells.
 *
 * @param columns - Array of column definitions; each column exposes `header` (rendered in the header) and `cell` (called with `(row, rowIndex)` to render body cells)
 * @param data - Array of row data to render
 * @param rowKey - Function that returns a unique key for a row given `(row, rowIndex)`
 * @param tableClassName - Optional className added to the outer Table element
 * @param headerRowClassName - Optional className added to the header TableRow
 * @param headerCellClassName - Optional className added to each header cell
 * @param bodyRowClassName - Optional className added to each body TableRow
 * @param bodyCellClassName - Optional className added to each body TableCell
 * @param headerClassName - Optional className added to the TableHeader container
 * @returns A table JSX element built from the provided columns and data
 */
export function DataTable<T>({
  columns,
  data,
  rowKey,
  tableClassName,
  headerRowClassName,
  headerCellClassName,
  bodyRowClassName,
  bodyCellClassName,
  headerClassName,
}: DataTableProps<T>) {
  return (
    <Table className={cn('custom-scrollbar', tableClassName)}>
      <TableHeader className={headerClassName}>
        <TableRow className={cn('hover:bg-transparent!', headerRowClassName)}>
          {columns.map((column, colIndex) => (
            <TableHead
              key={colIndex}
              className={cn(
                'bg-dark-400 text-purple-100 py-4 first:pl-5 last:pr-5',
                headerCellClassName,
              )}
            >
              {column.header}
            </TableHead>
          ))}
        </TableRow>
      </TableHeader>

      <TableBody>
        {data.map((row, rowIndex) => (
          <TableRow
            key={rowKey(row, rowIndex)}
            className={cn(
              'overflow-hidden rounded-lg border-b border-purple-100/5 hover:bg-dark-400/30! relative',
              bodyRowClassName,
            )}
          >
            {columns.map((column, colIndex) => (
              <TableCell
                key={colIndex}
                className={cn('py-4 first:pl-5 last:pr-5', bodyCellClassName)}
              >
                {column.cell(row, rowIndex)}
              </TableCell>
            ))}
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}